// apps/dashboard/src/components/SseEventList.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import JsonView from "./JsonView.vue";
import type { SseEventView } from "../utils/body.js";

const props = defineProps<{
  events: SseEventView[] | null;
  truncated?: boolean;
}>();

const events = computed<SseEventView[]>(() => props.events ?? []);

// 折叠状态按索引存。切换请求记录时必须清空，否则上一条的折叠会串到下一条。
const collapsed = ref<ReadonlySet<number>>(new Set());
watch(
  () => props.events,
  () => {
    collapsed.value = new Set();
  },
);

const isCollapsed = (index: number): boolean => collapsed.value.has(index);

const allCollapsed = computed(
  () => events.value.length > 0 && collapsed.value.size === events.value.length,
);

const toggle = (index: number): void => {
  const next = new Set(collapsed.value);
  if (!next.delete(index)) {
    next.add(index);
  }
  collapsed.value = next;
};

const toggleAll = (): void => {
  collapsed.value = allCollapsed.value
    ? new Set()
    : new Set(events.value.map((_, index) => index));
};
</script>

<template>
  <div v-if="events.length > 0" class="sse-events">
    <div class="sse-toolbar">
      <span class="sse-count">{{ events.length }} 个事件</span>
      <button type="button" class="sse-toggle-all" @click="toggleAll">
        {{ allCollapsed ? "全部展开" : "全部折叠" }}
      </button>
    </div>
    <p v-if="truncated" class="sub-note sse-truncated-note">
      流较长，仅采样了前部分事件，完整内容请用上游日志核对。
    </p>
    <article v-for="(evt, index) in events" :key="index" class="sse-event">
      <button
        type="button"
        class="sse-event-head"
        :aria-expanded="!isCollapsed(index)"
        @click="toggle(index)"
      >
        <span
          class="sse-event-caret"
          :class="{ 'is-collapsed': isCollapsed(index) }"
          aria-hidden="true"
        ></span>
        <span class="sse-event-index">{{ index + 1 }}</span>
        <span
          class="sse-event-name"
          :class="{ 'is-message': evt.event === 'message' }"
          >{{ evt.event }}</span
        >
        <span v-if="evt.id" class="sse-event-id">id: {{ evt.id }}</span>
      </button>
      <div v-show="!isCollapsed(index)" class="sse-event-body">
        <JsonView
          v-if="evt.jsonData !== null"
          :data="evt.jsonData as any"
        />
        <pre v-else class="sse-event-raw">{{ evt.data }}</pre>
      </div>
    </article>
  </div>
</template>

// apps/dashboard/src/components/detail/SseEventList.tsx
import { useState } from "react";
import { ChevronRight } from "lucide-react";
import type { SseEventView } from "../../lib/body";
import { JsonTree } from "./JsonTree";
import { cn } from "../../lib/cn";

/** SSE：逐帧折叠 + 全局折叠/展开，JSON 帧直接走树视图。 */
export const SseEventList = ({
  events,
  truncated,
  query = "",
}: {
  events: SseEventView[];
  truncated?: boolean;
  query?: string;
}) => {
  const [collapsed, setCollapsed] = useState<ReadonlySet<number>>(() => new Set());

  const allCollapsed = events.length > 0 && collapsed.size === events.length;

  const toggle = (index: number) =>
    setCollapsed((current) => {
      const next = new Set(current);
      if (!next.delete(index)) next.add(index);
      return next;
    });

  return (
    <div className="flex flex-col gap-2">
      <div className="flex items-center justify-between gap-2">
        <span className="font-mono text-[12px] text-fg-soft">{events.length} 个事件</span>
        <button
          type="button"
          onClick={() =>
            setCollapsed(allCollapsed ? new Set() : new Set(events.map((_, index) => index)))
          }
          className="rounded-sm px-1.5 py-0.5 text-[11px] text-accent hover:bg-accent-soft"
        >
          {allCollapsed ? "全部展开" : "全部折叠"}
        </button>
      </div>

      {truncated ? (
        <p className="m-0 text-[11px] text-fg-dim">
          流较长，仅采样了前部分事件，完整内容请用上游日志核对。
        </p>
      ) : null}

      <ol className="m-0 flex list-none flex-col gap-1.5 p-0">
        {events.map((event, index) => {
          const isCollapsed = collapsed.has(index);
          return (
            <li
              key={`sse-${index}`}
              className="overflow-hidden rounded-md border border-line bg-surface-2"
            >
              <button
                type="button"
                onClick={() => toggle(index)}
                aria-expanded={!isCollapsed}
                className="flex min-h-9 w-full items-center gap-2 px-2.5 py-1.5 text-left"
              >
                <ChevronRight
                  className={cn(
                    "size-3.5 shrink-0 text-fg-dim transition-transform duration-150",
                    !isCollapsed && "rotate-90",
                  )}
                />
                <span className="font-mono text-[11px] text-fg-dim">#{index + 1}</span>
                <span
                  className={cn(
                    "rounded-full px-1.5 py-px font-mono text-[11px] font-semibold",
                    event.event === "message"
                      ? "bg-surface-3 text-fg-soft"
                      : "bg-accent-soft text-accent-strong",
                  )}
                >
                  {event.event}
                </span>
                {event.id ? (
                  <span className="truncate font-mono text-[11px] text-fg-dim">
                    id: {event.id}
                  </span>
                ) : null}
              </button>

              {!isCollapsed ? (
                <div className="border-t border-line px-2.5 py-2">
                  {event.jsonData !== null ? (
                    <JsonTree data={event.jsonData} query={query} />
                  ) : (
                    <pre className="m-0 whitespace-pre-wrap break-words font-mono text-[12px] leading-relaxed text-fg">
                      {event.data}
                    </pre>
                  )}
                </div>
              ) : null}
            </li>
          );
        })}
      </ol>
    </div>
  );
};
